name: cleanup outdated companion branches

on:
  schedule:
    - cron: '0 16 * * 0' # 毎週月曜日の 1:00 JST（UTC 16:00）に実行
  workflow_dispatch:

permissions: {}

jobs:
  cleanup-branches:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      contents: write # リモートブランチ削除

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # すべてのブランチ情報を取得

      # 古いコンパニオンブランチのクリーンアップ
      - name: Cleanup outdated companion branches
        run: |
          # "companion_" プレフィックスを持つリモートブランチ一覧を取得
          git branch -r --format="%(refname:lstrip=3)" | grep companion_ | while read -r branch; do

            # 各ブランチの最終コミット日時を UNIX タイムスタンプ(秒単位)で取得
            last_commit_date_timestamp=$(git log -1 --format=%ct "origin/$branch")

            # 現在の時刻を UNIX タイムスタンプ (秒単位) で取得
            now_timestamp=$(date +%s)

            # 最終コミットからの経過時間を計算
            age=$((now_timestamp - last_commit_date_timestamp))

            # 最終コミットから30日 (2592000秒) 経過している場合、削除対象とする
            if [ "$age" -gt 2592000 ]; then
              echo "Deleting outdated branch: $branch"
              git push origin --delete "$branch"
            fi
          done