name: compare screenshot with comment

on:
  pull_request:

permissions: {}

jobs:
  compare-and-comment:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      contents: write # push branches
      pull-requests: write # comment on PRs

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper

      # ダウンロード先のブランチを決定
      - name: Determine correct branch to download screenshots from
        id: determine-branch
        run: |
          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
          HEAD_BRANCH="${{ github.head_ref }}"
          # デフォルトのダウンロード先を PR のマージ先ブランチに設定
          DOWNLOAD_BRANCH="$BASE_BRANCH"
          # BASE_BRANCH に "develop" または "/develop" が含まれていない場合
          if [[ ! "$BASE_BRANCH" =~ "develop" ]]; then
            # HEAD_BRANCH が "sample/*" のような形式であることを想定し、接頭辞を取得
            PREFIX=$(echo "$HEAD_BRANCH" | cut -d'/' -f1)
            # プレフィックスの名前に合わせて "/develop" を追加
            DOWNLOAD_BRANCH="${PREFIX}/develop"
          fi
          # 環境変数に設定
          echo "DOWNLOAD_BRANCH=${DOWNLOAD_BRANCH}" >> "$GITHUB_ENV"
          # ログ出力
          echo "Determined DOWNLOAD_BRANCH: $DOWNLOAD_BRANCH"

      # 過去のスクリーンショットアーティファクトをダウンロード（エラー無視）
      - name: Download previous screenshots
        uses: dawidd6/action-download-artifact@v8
        continue-on-error: true
        with:
          name: screenshots
          workflow: store_screenshots.yml
          branch: ${{ env.DOWNLOAD_BRANCH }}

      # ファイルの整理
      - name: Organize downloaded files
        run: |
          # "screenshots"ディレクトリを作成し、カレントディレクトリ(.)直下にあるPNGファイルを移行する
          mkdir -p screenshots
          find . -maxdepth 1 -name "*.png" -exec mv {} screenshots/ \; || echo "No PNG files to move."

      # スクリーンショット比較テストを実行
      - name: Compare screenshot test
        id: compare-screenshot-test
        run: |
          ./gradlew compareRoborazziDebug --stacktrace

      # スクリーンショット差分を保存
      - name: Save screenshot diff
        run: |
          # "screenshot-diff"ディレクトリを作成し、差分スクリーンショットをコピーする
          mkdir -p screenshot-diff
          find **/build/outputs/roborazzi/ -type f -exec cp {} screenshot-diff/ \; || echo "No screenshot diff files found to save."

      # 有効なファイルが存在するか確認
      - id: check-if-there-are-valid-files
        name: Check if there are valid files
        shell: bash
        run: |
          # 差分画像 (*_compare.png)を検索し、配列に格納
          mapfile -t files_to_add < <(find ./screenshot-diff -type f -name "*_compare.png")
          exist_valid_files="false"
          # 1つでも有効なファイルがある場合は、ループを抜ける
          for file in "${files_to_add[@]}"; do
            if [[ $file =~ ^[a-zA-Z0-9_./-]+$ ]]; then
              exist_valid_files="true"
              break
            fi
          done
          # 結果をGITHUB_OUTPUTに書き込む
          echo "exist_valid_files=$exist_valid_files" >> "$GITHUB_OUTPUT"

      # 差分をコミットしてコンパニオンブランチにプッシュ
      - id: push-screenshot-diff
        shell: bash
        if: steps.check-if-there-are-valid-files.outputs.exist_valid_files == 'true'
        env:
          # ブランチ名を設定: feature/new-ui の場合 → companion_feature/new-ui
          BRANCH_NAME: companion_${{ github.head_ref || github.run_id }}
        run: |
          # "screenshot-diff"ディレクトリ内の差分ファイルを取得し、git addする
          files_to_add=$(find ./screenshot-diff -type f -name "*_compare.png")
          for file in $files_to_add; do
            git add "$file"
          done
          # 差分をコミット・プッシュ
          git config --global user.name ScreenshotBot
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          git commit -m "Add screenshot diff"
          git push origin HEAD:"refs/heads/$BRANCH_NAME" -f

      # 差分レポートを生成
      - id: generate-diff-reports
        name: Generate diff reports
        if: steps.check-if-there-are-valid-files.outputs.exist_valid_files == 'true'
        shell: bash
        env:
          BRANCH_NAME: companion_${{ github.head_ref || github.run_id }}
        run: |
          # コンパニオンブランチから"screenshot-diff"ディレクトリ内の差分ファイルを取得
          files=$(find ./screenshot-diff -type f -name "*_compare.png")
          # 複数行の出力に対応するための区切り文字を生成
          # ランダムな16進数の8文字 (例: d1e2f3a4)を使用し、一意の識別子として扱う
          delimiter="$(openssl rand -hex 8)"
          # 一時ファイルを作成し、Markdownのヘッダーを記述
          temp_output_file=$(mktemp)
          {
            echo "reports<<${delimiter}"
            echo "<!-- screenshot-diff-comment -->"
            echo "| ファイル名 | イメージ |"
            echo "|-------|-------|"
          } > "$temp_output_file"
          # 差分ファイルごとにMarkdownの表に追加
          for file in $files; do
            fileName=$(basename "$file" | sed -r 's/(.{20})/\1<br>/g')
            echo "| [$fileName](https://github.com/${{ github.repository }}/blob/$BRANCH_NAME/screenshot-diff/${file#./screenshot-diff/}) | ![](https://github.com/${{ github.repository }}/blob/$BRANCH_NAME/screenshot-diff/${file#./screenshot-diff/}?raw=true) |" >> "$temp_output_file"
          done
          # 区切り文字を追加
          echo "${delimiter}" >> "$temp_output_file"
          # ファイルをGITHUB_OUTPUTに書き込む
          cat "$temp_output_file" >> "$GITHUB_OUTPUT"

      # 既存のコメントを検索
      - id: find-comment
        name: Find existing comment
        uses: peter-evans/find-comment@v3
        with:
          issue-number: ${{ github.event.number }}
          body-includes: "<!-- screenshot-diff-comment -->" # 一意の識別子で既存コメントを検索

      # プルリクエストにコメントを追加または更新
      - name: Add or update comment on PR
        uses: peter-evans/create-or-update-comment@v4
        if: steps.generate-diff-reports.outputs.reports != ''
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.number }}
          body: ${{ steps.generate-diff-reports.outputs.reports }}
          edit-mode: replace