name: compare screenshot with comment

on:
  pull_request:

jobs:
  compare-and-comment:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      contents: write # push branches
      pull-requests: write # comment on PRs

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper

      # ダウンロード先のブランチを決定
      - name: Determine correct branch to download screenshots from
        id: determine-branch
        run: |
          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
          HEAD_BRANCH="${{ github.head_ref }}"
          # デフォルトのダウンロード先を PR のマージ先ブランチに設定
          DOWNLOAD_BRANCH="$BASE_BRANCH"
          # BASE_BRANCH に "develop" または "/develop" が含まれていない場合
          if [[ ! "$BASE_BRANCH" =~ "develop" ]]; then
            # HEAD_BRANCH が "sample/*" のような形式であることを想定し、接頭辞を取得
            PREFIX=$(echo "$HEAD_BRANCH" | cut -d'/' -f1)
            # プレフィックスの名前に合わせて "/develop" を追加
            DOWNLOAD_BRANCH="${PREFIX}/develop"
          fi
          # 環境変数に設定
          echo "DOWNLOAD_BRANCH=${DOWNLOAD_BRANCH}" >> "$GITHUB_ENV"
          # ログ出力
          echo "Determined DOWNLOAD_BRANCH: $DOWNLOAD_BRANCH"

      # 過去のスクリーンショットアーティファクトをダウンロード
      - name: Download previous screenshots
        uses: dawidd6/action-download-artifact@v8
        with:
          name: screenshots_upload-name/develop
          workflow: store_screenshots.yml
          branch: ${{ env.DOWNLOAD_BRANCH }}

      # ファイルを移動
      - name: Move downloaded files
        id: move-downloaded-files
        run: |
          # "screenshots"ディレクトリを作成し、カレントディレクトリ(.)直下にあるPNGファイルを移行する
          mkdir -p screenshots
          find "$GITHUB_WORKSPACE" -maxdepth 1 -name "*.png" -exec mv {} screenshots/ \;

          # PNGファイルが存在するか確認
          if [[ -z "$(ls -A screenshots)" ]]; then
            echo "No PNG files found."
            echo "PREVIOUS_SCREENSHOT_FOUND=false" >> "$GITHUB_OUTPUT"
          else
            echo "PNG files found."
            echo "PREVIOUS_SCREENSHOT_FOUND=true" >> "$GITHUB_OUTPUT"
          fi
        shell: bash

        # スクリーンショット比較テストを実行
      - name: Compare screenshot test
        id: compare-screenshot-test
        if: steps.move-downloaded-files.outputs.PREVIOUS_SCREENSHOT_FOUND == 'true'
        run: |
          ./gradlew compareRoborazziDebug --stacktrace

      # スクリーンショット差分を検索
      - name: Find screenshot diff
        shell: bash
        run: |
          # "screenshot-diff"ディレクトリを作成し、差分ファイルをコピー
          mkdir -p screenshot-diff
          find **/build/outputs/roborazzi/ -type f -name "*_compare.png" -exec cp {} screenshot-diff/ \;

          # 差分ファイルが存在するか確認
          if [[ -z "$(ls -A screenshot-diff)" ]]; then
            echo "No screenshot diff files found."
            echo "SCREENSHOT_DIFF_FOUND=false" >> "$GITHUB_ENV"
            exit 0
          fi
          echo "Screenshot diff files found."
          echo "SCREENSHOT_DIFF_FOUND=true" >> "$GITHUB_ENV"

      # 差分をコミットしてコンパニオンブランチにプッシュ
      - name: Push screenshot diff
        if: env.SCREENSHOT_DIFF_FOUND == 'true'
        shell: bash
        env:
          # ブランチ名を設定: feature/new-ui の場合 → companion_feature/new-ui
          BRANCH_NAME: companion_${{ github.head_ref }}
        run: |
          # "screenshot-diff"ディレクトリ内の差分ファイルを取得し、git addする
          files_to_add=$(find ./screenshot-diff -type f -name "*_compare.png")
          for file in $files_to_add; do
            git add "$file"
          done
          # 差分をコミット・プッシュ
          git config --global user.name ScreenshotBot
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          git commit -m "Add screenshot diff"
          git push origin HEAD:"refs/heads/$BRANCH_NAME" -f

      # 差分レポートを生成
      - name: Generate diff reports
        if: env.SCREENSHOT_DIFF_FOUND == 'true'
        id: generate-diff-reports
        shell: bash
        env:
          BRANCH_NAME: companion_${{ github.head_ref || github.run_id }}
        run: |
          # コンパニオンブランチから"screenshot-diff"ディレクトリ内の差分ファイルを取得
          files=$(find ./screenshot-diff -type f -name "*_compare.png")
          # 複数行の出力に対応するための区切り文字を生成
          # ランダムな16進数の8文字 (例: d1e2f3a4)を使用し、一意の識別子として扱う
          delimiter="$(openssl rand -hex 8)"
          # 一時ファイルを作成し、Markdownのヘッダーを記述
          temp_output_file=$(mktemp)
          {
            echo "reports<<${delimiter}"
            echo "<!-- screenshot-diff-comment -->"
            echo "| ファイル名 | イメージ |"
            echo "|-------|-------|"
          } > "$temp_output_file"
          # 差分ファイルごとにMarkdownの表に追加
          for file in $files; do
            fileName=$(basename "$file" | sed -r 's/(.{20})/\1<br>/g')
            echo "| [$fileName](https://github.com/${{ github.repository }}/blob/$BRANCH_NAME/screenshot-diff/${file#./screenshot-diff/}) | ![](https://github.com/${{ github.repository }}/blob/$BRANCH_NAME/screenshot-diff/${file#./screenshot-diff/}?raw=true) |" >> "$temp_output_file"
          done
          # 区切り文字を追加
          echo "${delimiter}" >> "$temp_output_file"
          # ファイルをGITHUB_OUTPUTに書き込む
          cat "$temp_output_file" >> "$GITHUB_OUTPUT"

      # 既存のコメントを検索
      - name: Find existing comment
        if: env.SCREENSHOT_DIFF_FOUND == 'true'
        id: find-comment
        uses: peter-evans/find-comment@v3
        with:
          issue-number: ${{ github.event.number }}
          body-includes: "<!-- screenshot-diff-comment -->" # 一意の識別子で既存コメントを検索

      # プルリクエストにコメントを追加または更新
      - name: Add or update comment on PR
        if: env.SCREENSHOT_DIFF_FOUND == 'true'
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.number }}
          body: ${{ steps.generate-diff-reports.outputs.reports }}
          edit-mode: replace
